# Generated by Django 2.2.18 on 2021-02-06 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20210206_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 7, 10, 55, 142176, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
