# Generated by Django 2.2.18 on 2021-02-23 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20210206_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 5, 38, 14, 70643, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
