# Generated by Django 2.2.18 on 2021-02-07 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20210207_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 3, 27, 43, 740796, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
