# Generated by Django 2.2.18 on 2021-02-07 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20210207_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 3, 39, 27, 852781, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
