# Generated by Django 2.2.18 on 2021-02-22 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20210222_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 10, 41, 702257, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
