# Generated by Django 2.2.18 on 2021-02-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20210223_1338'),
        ('comments', '0016_auto_20210222_1710'),
    ]

    operations = [
    ]
